### ISSUE TITLE
check only published tag?

### ISSUE THREAD

**Issue by lukedoomer** [gvalkov/rsstail.py#11]
Could you add a flag to toggle checking pubhlished tag only and ignore updated tag? I don't need the same article get updated being outputed my console.

**Comment by gvalkov** [comment]
The `-q, --unique` option was added in 06ce6f47bcc16242737a1eac7b1c408b6f925c6a. It will prevent rsstail from showing posts that have already been shown, based on the post's ID. This feature is available in rsstai 0.4.0. Thanks for the feature request.
