### ISSUE TITLE
Linefeeds not working in --format ?

### ISSUE THREAD

**Issue by fuzzy76** [gvalkov/rsstail.py#12]
No matter what I do, rsstail outputs '/n' literally instead of making it into a linefeed.  Even the documentation examples shows this behaviour. OS X and Python 2.7.

**Comment by gvalkov** [comment]
Hello. Thanks for the catch - I had indeed overlooked this. Fixed in 732abb425b56841a5533dc7e06bbfd394b7d1482 - I'll roll out a new release tomorrow.
